name: dahis_mobile
description: dahi's One mobile application built with Flutter
publish_to: 'none'
version: 1.0.1+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.2
  package_info_plus: ^8.0.0
  cloud_firestore: ^5.4.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  provider: ^6.1.2
  nfc_manager: 3.4.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/characters/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0a0a0f"
  adaptive_icon_foreground: "assets/icon/icon.png"
  remove_alpha_ios: true

